# Generated by Django 5.0.1 on 2024-01-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phoneno', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
